//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvBand.Tests.Dto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Json {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Json() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvBand.Tests.Dto.Json", typeof(Json).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;tv&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;Watch TV&quot;
        ///    },
        ///    &quot;satellite&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;Watch satellite&quot;
        ///    },
        ///    &quot;hdmi1&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;HDMI 1&quot;
        ///    },
        ///    &quot;hdmi2&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;HDMI 2&quot;
        ///    },
        ///    &quot;hdmi3&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;HDMI 3&quot;
        ///    },
        ///    &quot;hdmiside&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;HDMI side&quot;
        ///    },
        ///    &quot;ext1&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;EXT 1&quot;
        ///    },
        ///    &quot;ext2&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;EXT 2&quot;
        ///    },
        ///    &quot;ypbpr&quot;:
        ///    {
        ///        &quot;name&quot;: &quot;Y Pb Pr&quot;
        ///    },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
    }
}
